// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUVe3TUZzj6EAsre0qE6QFK0mKe5i4bvc',
    appId: '1:242295209989:web:ea8c44e6bcd85f19491c6c',
    messagingSenderId: '242295209989',
    projectId: 'apkrastreo-c6f87',
    authDomain: 'apkrastreo-c6f87.firebaseapp.com',
    databaseURL: 'https://apkrastreo-c6f87-default-rtdb.firebaseio.com',
    storageBucket: 'apkrastreo-c6f87.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp84UjsPHx_6UbFjCyKRI_0HzQ2JUvh0w',
    appId: '1:242295209989:android:b7afb628c54a3794491c6c',
    messagingSenderId: '242295209989',
    projectId: 'apkrastreo-c6f87',
    databaseURL: 'https://apkrastreo-c6f87-default-rtdb.firebaseio.com',
    storageBucket: 'apkrastreo-c6f87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArFHuYWY2iEdbVONA8AtsYzYlNrbFMSmY',
    appId: '1:242295209989:ios:67bf25d104105e35491c6c',
    messagingSenderId: '242295209989',
    projectId: 'apkrastreo-c6f87',
    databaseURL: 'https://apkrastreo-c6f87-default-rtdb.firebaseio.com',
    storageBucket: 'apkrastreo-c6f87.firebasestorage.app',
    iosBundleId: 'com.example.trackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArFHuYWY2iEdbVONA8AtsYzYlNrbFMSmY',
    appId: '1:242295209989:ios:67bf25d104105e35491c6c',
    messagingSenderId: '242295209989',
    projectId: 'apkrastreo-c6f87',
    databaseURL: 'https://apkrastreo-c6f87-default-rtdb.firebaseio.com',
    storageBucket: 'apkrastreo-c6f87.firebasestorage.app',
    iosBundleId: 'com.example.trackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUVe3TUZzj6EAsre0qE6QFK0mKe5i4bvc',
    appId: '1:242295209989:web:e59f8c57a577f0ff491c6c',
    messagingSenderId: '242295209989',
    projectId: 'apkrastreo-c6f87',
    authDomain: 'apkrastreo-c6f87.firebaseapp.com',
    databaseURL: 'https://apkrastreo-c6f87-default-rtdb.firebaseio.com',
    storageBucket: 'apkrastreo-c6f87.firebasestorage.app',
  );
}